#!/bin/bash

SVC_NAME="pjc-mc"

if [ "$INSTALL_DEPS" == "1" ] ; then
    pip install -r /opt/$SVC_NAME/requirements.txt
fi

update-rc.d $SVC_NAME defaults

if [ "$NO_START" != "1" ] ; then
    service $SVC_NAME start
fi
