#!/bin/bash

if [ "$INSTALL_DEPS" == "1" ] ; then
    apt-get install pip
    pip install tornado
fi

update-rc.d pjc-compmgr defaults

if [ "$START_SERVICE" == "1" ] ; then
    service start pjc-compmgr
fi