#!/bin/bash

if [ "$INSTALL_DEPS" == "1" ] ; then
    pip install tornado
fi

SVC_NAME="pjc-compmgr"

update-rc.d $SVC_NAME defaults

if [ "$START_SERVICE" == "1" ] ; then
    service $SVC_NAME start
fi